url: https://rebelay.com

netlifycms: true

sass:
  dir: _sass
  style: compressed  

paths:
  uploads: "assets/images"
css_dir: "/style"

collections:
  posts:
    output: true
    permalink: /:year/:month/:title
  pages:
    output: true
    permalink: /:title

picture:
  source: "/"
  output: "generated/"
  suppress_warnings: true

comments:
 body_font_family: Add the font code block on the configurations menu
 display_font_family: Add the font code block on the configuratios menu
 preview_image: Image to be shown when sharing the site on social networks
 custom_css_code_block: 'Add custom styles to your site (SCSS-compatible). This theme uses TailwindCSS 2.1. Important: You might require the assistance of a developer.'

plugins:
  - jekyll-sitemap  
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-last-modified-at
  - jekyll_picture_tag


channels:
  - "Facebook"
  - "Instagram"
  - "Twitter"
  - "WhatsApp"
  - "Github"
  - "Snapchat"
  - "LinkedIn"
  - "Skype"
  - "Telegram"
  - "Signal"
  - "Messenger"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore