site_info:
  site_url: 'https://rebelay.com'
  address:
  email: 
  phone: 
  social:
    - channel: "Facebook"      
      url: 'https://facebook.com/rebelay.canyoning'    
    - channel: "Instagram"      
      url: 'https://instagram.com/rebelay.canyoning'
branding:
  site_title: 'Re:belay Canyoning'
  nav_logo_image: /assets/images/rebelay-nav-logo-dark.png
  footer_logo_image: /assets/images/rebelay-icon-dark.png
  preview_image: /assets/images/preview-rebelay-logo-dark.jpg  
navigation:
  menus:
    - name: About
      url: /about
      is_dropdown: false
      style_as_button: false
      submenus:
        - name:
          url:
    - name: Articles
      url: /articles
      is_dropdown: false
      style_as_button: false
      submenus:
        - name: Item 1
          url: /        
    - name: Calendar
      url: /events
      is_dropdown: false
      style_as_button: false
      submenus:
        - name: Item 1
          url: /        
    - name: Merch
      url: /shop
      is_dropdown: false
      style_as_button: false
      submenus:
        - name: Item 1
          url: /              
seo:
  site_description_text:
  keywords:
configuration:
  head_code_block: >-
    
  body_code_block:
  custom_css_code_block:   