site_info:
  site_url: 'https://rebelay.com'
  address:
  email: 
  phone: 
  social:
    - channel: "Facebook"      
      url: 'https://facebook.com/rebelay.canyoning'    
    - channel: "Instagram"      
      url: 'https://instagram.com/rebelay.canyoning'
branding:
  site_title: 'Re:belay Canyoning'
  nav_logo_image: /assets/images/rebelay-nav-logo-dark.png
  footer_logo_image: /assets/images/rebelay-icon-dark.png
  preview_image: /assets/images/preview-rebelay-logo-dark.jpg  
navigation:
  menus:
    - name: About
      url: /about
      is_dropdown: false
      style_as_button: false
      submenus:
        - name:
          url:
    - name: Articles
      url: /articles
      is_dropdown: false
      style_as_button: false
      submenus:
        - name: Item 1
          url: /        
    # - name: Resources
    #   url: /resources
    #   is_dropdown: false
    #   style_as_button: false
    #   submenus:
    #     - name: Item 1
    #       url: /        
    - name: Merch
      url: /shop
      is_dropdown: false
      style_as_button: false
      submenus:
        - name: Item 1
          url: /              
seo:
  site_description_text:
  keywords:
configuration:
  head_code_block: >-
    <script type="module" src="https://cdn.jsdelivr.net/npm/@justinribeiro/lite-youtube@1.5.0/lite-youtube.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alexandria:wght@300;400;500;600&family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet preload" onload="this.rel = 'stylesheet'" as="style" crossorigin="anonymous" type="text/css">
  body_code_block:
  custom_css_code_block:   