general:
  site_url: 
  address:
  email:
  phone:
  social:
    - channel: "Facebook"
      add_to_chat_bubble: false
      url: 'https://facebook.com'
    - channel: "WhatsApp"
      add_to_chat_bubble: true
      url: 'https://facebook.com'
    - channel: "Messenger"
      add_to_chat_bubble: true
      url: 'https://facebook.com'
branding:
  site_title: 'Re:belay Canyoning'
  nav_logo_image: /assets/images/rebelay-logo-with-tagline-light-full-width.png
  footer_logo_image:
  preview_image:
navigation:
  menus:
    - name: About
      url: /about
      is_dropdown: false
      style_as_button: false
      submenus:
        - name:
          url:
    - name: Articles
      url: '#'
      is_dropdown: false
      style_as_button: false
      submenus:
        - name: Item 1
          url: /        
    - name: Community
      url: '#'
      is_dropdown: false
      style_as_button: false
      submenus:
        - name: Item 1
          url: /        
    - name: Merch
      url: '#'
      is_dropdown: false
      style_as_button: false
      submenus:
        - name: Item 1
          url: /
        - name: Item 2
          url: /
        - name: Item 3
          url: /
seo:
  site_description_text:
  keywords:
configuration:
  head_code_block: >-
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alexandria:wght@300;400;500;600&family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet preload" onload="this.rel = 'stylesheet'" as="style" crossorigin="anonymous" type="text/css">
  body_code_block:
  custom_css_code_block:   