backend:
  name: git-gateway
  branch: main
media_folder: "assets/images"
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}/{{month}}/{{display_title}}"
    fields:
      - {label: "Layout", name: "layout", widget: 'select', options: ["post","legal","default"]}
      - {label: "SEO Title", name: "title", widget: "string"}
      - {label: "Display Title", name: "display_title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Feature Image", name: "feature_image", widget: "image", default: "/assets/images/placeholder.jpg"}
      - {label: "Author", name: "author", widget: "select", options: ['gus','jake','imin']}
      - {label: "Gallery", name: "gallery", widget: "list", fields: [{label: 'Gallery Image', name: 'image', widget: image},{label: 'Alt Text', name: 'alt_text', widget: 'string'}, {label: 'Caption', name: 'caption', widget: 'text'}]}